---
version: 0.2
phases:
  install:
    commands:
      - apt-get update && apt-get -y install python-pip jq && pip install --upgrade python && pip install --upgrade awscli
  pre_build:
      commands:
      - printenv
      - TAG="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build --tag $REPOSITORY_URI:$TAG .
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$TAG
      - cat batch-job-definition.json | jq ".jobDefinitionName=\"$JOB_DEFINITION_NAME\" | .containerProperties.jobRoleArn=\"$JOB_DEFINITION_ROLE_ARN\" | .containerProperties.environment[0].value=\"$S3_BUCKET_NAME\" | .containerProperties.image=\"$REPOSITORY_URI:$TAG\"" > /tmp/job.json
      - JOB_DEF_ARN=$(aws batch register-job-definition --cli-input-json file:///tmp/job.json | jq '.jobDefinitionArn')
      - echo $JOB_DEF_ARN
      - RULE_ARN=$(aws events put-rule --name $JOB_DEFINITION_NAME --schedule-expression "cron(0/5 * * * ? *)" --state ENABLED | jq '.RuleArn')
      - echo $RULE_ARN
      - cat event-target.json | jq ".Rule=\"$JOB_DEFINITION_NAME\" | .Targets[0].BatchParameters.JobDefinition=$JOB_DEF_ARN | .Targets[0].RoleArn=\"$CWE_SUBMIT_BATCH_JOB_ROLE_ARN\" | .Targets[0].Id=\"$JOB_DEFINITION_NAME\" | .Targets[0].Arn=\"$JOB_QUEUE_ARN\"" > /tmp/event-target.json
      - cat /tmp/event-target.json
      - aws events put-targets --cli-input-json file:///tmp/event-target.json
